### ISSUE TITLE
[TiKV-BR]  Parameter Identification ERROR and Command Prompt  inaccurate when not set --dst-api-version

### ISSUE THREAD

**Issue by yongpan0709** [tikv/migration#109]
### 1. Describe the bug

![yNZNKkzDwA](https://user-images.githubusercontent.com/84337599/170234644-2b987da0-a9a1-4b3a-91fb-6512184c0c1d.jpg)

### 2. Minimal reproduce step (Required)
As the screenshot.

### 3. What did you see instead (Required)
dst-api-version identifys  to dot ".". 

### 4. What did you expect to see? (Required)
dst-api-version only supports: V1, V1TTL, V2

### 5. What is your migration tool and TiKV version? (Required)
- TiKV BR: Release Version: d8c0fb1
Git Commit Hash: d8c0fb1ba6f5d96dd43d8806c3082e152ef77696
Git Branch: main
Go Version: go1.16.5
UTC Build Time: 2022-05-25 09:30:18
Race Enabled: false

**Comment by haojinming** [comment]
The behaviour is changed, if user does not specify `dst-api-version`, tikv-br will regard use `api-version` in tikv cluster as `dst-api-version`. Please see https://github.com/tikv/migration/pull/103/commits/3c7d8ea6d6d8afa08c35a1df12e53457055a6e18.
