### ISSUE TITLE
[TiKV-BR] BR failed to restore when restored V1TTL data, with Error: [BR:KV:ErrKVKeyNotInRegion]key not in region

### ISSUE THREAD

**Issue by yongpan0709** [tikv/migration#111]
### 1. Describe the bug
BR failed to restore when restored V1TTL data, with Error: [BR:KV:ErrKVKeyNotInRegion]key not in region

### 2. Minimal reproduce step (Required)
1. Deploy V1+TTL Cluster v6.1.0
2. Import some data
3. Backup -dst-api-version V1TTL
4. Backup -dst-api-version V2
5. Restore V2 data on the same cluster, expect to fail
6. Restore V1TTL data on the same cluster, expect to success

### 3. What did you see instead (Required)
Failed to restore V1TTL data

### 4. What did you expect to see? (Required)
Should restore V1TTL data successfully.

### 5. What is your migration tool and TiKV version? (Required)

- TiKV:  ./tikv-server -V
TiKV 
Release Version:   6.1.0-alpha
Edition:           Community
Git Commit Hash:   50c2abf87fd144a739ba7ccb70b4100f2c0d92f9
Git Commit Branch: heads/refs/tags/v6.1.0-alpha
UTC Build Time:    2022-05-25 14:54:48
Rust Version:      rustc 1.60.0-nightly (1e12aef3f 2022-02-13)
Enable Features:   pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine cloud-aws cloud-gcp cloud-azure
Profile:           dist_release

- TiKV BR: ./tikv-br --version
Release Version: 7f90200
Git Commit Hash: 7f90200c6d4db411910887a15751ac1da76017cc
Git Branch: pr103
Go Version: go1.16.5
UTC Build Time: 2022-05-26 01:59:28
Race Enabled: false

**Comment by haojinming** [comment]
This issue is fixed in [156210b451918f439d817c1cc56f114a20f15c28](https://github.com/tikv/migration/pull/103/commits/156210b451918f439d817c1cc56f114a20f15c28) of pr #107
