### ISSUE TITLE
cdc: Increase test coverage

### ISSUE THREAD

**Issue by pingyu** [tikv/migration#134]
### 1. Describe the bug

The test coverage is low (totally about 59.67% for master). We should increase it.
See https://app.codecov.io/gh/tikv/migration.
<img width="546" alt="image" src="https://user-images.githubusercontent.com/1907938/175323156-8f682fdf-7aa4-40fc-81e6-b5cc728f1dca.png">

### 5. What is your migration tool and TiKV version? (Required)

- TiKV:
- TiKV CDC:
- TiKV BR:
- TiKV Online Bulk Load:

**Comment by zeminzhou** [comment]
TiKV-CDC also need more test case for integration test.
