### ISSUE TITLE
cdc: add GC related procedure

### ISSUE THREAD

**Issue by pingyu** [tikv/migration#139]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The GC related procedure of TiKV-CDC is expected to be:

1. On create / resume changefeed, set TiKV-CDC's `service safepoint` to changefeed's `start-ts` when it is not zero. If failed (when the `service safepoint` is lower than `min(all service safepoints)`, the creation / resume of changefeed is failed.

2. Before setting every checkpoint, set `service safepoint` to the `checkpoint-ts`. If failed (would happen when `start-ts` is zero that the changefeed is synchronizing from the beginning), log a warning and continue, trying to set a larger `service safepoint` in next round.

3. TTL of `service safepoint` defaults to 24 hours (configurable). Which means that a changefeed can be resumed within 24 hours. After that, the changefeed is dead. Synchronize from the beginning, or another BR backup & restore, is required.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by ystaticy** [comment]
add some more message:

in PD ```UpdateServiceGCSafePoint``` function: 
when ``` req.serviceSafepoint < min(all service safepoint) ```,will return error.
but if  ```min(all service safepoint) < req.serviceSafepoint < serviceID.lastServiceSafepoint``` ,it will not return error.

So , we can change ```when the service safepoint is lower than GC safepoint or last service safepoint```
to ```when the service safepoint is lower than min(all service safepoint) ```.

**Comment by pingyu** [comment]
> add some more message:
> 
> in PD `UpdateServiceGCSafePoint` function: when `req.serviceSafepoint < min(all service safepoint)`,will return error. but if `min(all service safepoint) < req.serviceSafepoint < serviceID.lastServiceSafepoint` ,it will not return error.
> 
> So , we can change the first item in above describe: `when the service safepoint is lower than GC safepoint or last service safepoint` to `when the service safepoint is lower than min(all service safepoint) `.

OK, thanks. The description of updated.

**Comment by pingyu** [comment]
The current codes meet GC requirement and no change is needed (except for https://github.com/tikv/migration/issues/172).
