### ISSUE TITLE
Inconsistent data found after cdc finish.

### ISSUE THREAD

**Issue by haojinming** [tikv/migration#149]
### 1. Describe the bug

Inconsistent value is found in dst tikv cluster after cdc process finish.

### 2. Minimal reproduce step (Required)
1. Start two tikv-cluster, one is source with cdc server, the other is cdc destination.
2.  Create changefeed with `tikv-cdc`
3.  Run case `rawkv_cdc_correctness_put` in pr https://github.com/pingcap/endless/pull/721, with 1kw keys.
4. Result show that the checksum in src and dst are not the same.
5. Scan all data show that the first value is sync to dst instead of the second.
![cvvDvtQK4g](https://user-images.githubusercontent.com/10524249/177901425-90ca99e6-4c58-47da-92bb-078fbf84fee5.jpg)

### 5. What is your migration tool and TiKV version? (Required)

- TiKV CDC:

**Comment by pingyu** [comment]
Fixed by https://github.com/tikv/migration/pull/155.
