### ISSUE TITLE
br: Hide "--check-requirements"

### ISSUE THREAD

**Issue by pingyu** [tikv/migration#157]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Hide "--check-requirements" option, and remove prompt of using "--check-requirements" when version mismatch is met.

Use `tikv-br` on a mismatch TiKV (e.g, on TiKV of v5) is an undefined action, even cause TiKV panic (see https://github.com/tikv/tikv/issues/12015). Should be used in caution, and not for common users.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by pingyu** [comment]
cc @haojinming

**Comment by haojinming** [comment]
Issue is fixed in pr #156
