### ISSUE TITLE
cdc: Speed up integrated tests

### ISSUE THREAD

**Issue by pingyu** [tikv/migration#295]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The integrated test cost almost one hour. It's quite inefficiency for waiting CI to check the correctness of PR.

**Describe the feature you'd like:**

We should try to speed up it.

**Describe alternatives you've considered:**

* Separate `make integration_test` to several sub-targets, and create jenkins steps for each one to run parallel.
  * TiFlow use a groovy ([here](https://github.com/PingCAP-QE/ci/blob/main/jenkins/pipelines/ci/ticdc/integration_test_common.groovy)) to run each test case as a step (see [here](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/16502/pipeline/135/)). It is great but we may need some help to do this.
* Combine some test cases to one to reduce the cost of establishing & destroying cluster (refer to [available test](https://github.com/tikv/migration/blob/main/cdc/tests/integration_tests/availability/run.sh)).
* Inspect some long test cases to see is there any change to cut some time.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by pingyu** [comment]
@zeminzhou @haojinming PTAL. How do you think ?

**Comment by haojinming** [comment]
It’s a great idea to make the integration test run parallelly if it's possible. May need create cluster for every parallel task?

**Comment by pingyu** [comment]
Yes. In current codes the cluster is setup before every test case, and destroyed after.
And the parallel tasks of jenkins are executed in isolated environment. They don't interfere each others.

**Comment by zeminzhou** [comment]
That's good. And I think the easiest way is dividing all tests into multiple groups and runing parallel.
