### ISSUE TITLE
br: will support txn mode?

### ISSUE THREAD

**Issue by qiaohao9** [tikv/migration#307]
## Feature Request

Is any plan that supports mode-txn?

**Describe the feature you'd like:**

Support backup tikv-txn data online.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by pingyu** [comment]
Not yet.

TiDB BR has a plan to support, please refer to https://github.com/pingcap/tidb/issues/38506.
