### ISSUE TITLE
Can the tidb-operator deploy RawKV CDC?

### ISSUE THREAD

**Issue by Smityz** [tikv/migration#401]

**Comment by pingyu** [comment]
No.
However, you can implement a workaround by deploying the `ticdc` component but using an image of RawKV CDC.

**Comment by Smityz** [comment]
Do we provide an official image? How about provide one.

**Comment by pingyu** [comment]
Not yet.
OK let me see see.

**Comment by Smityz** [comment]
😁 let us do this together
