### ISSUE TITLE
How to check whether replication has caught up?

### ISSUE THREAD

**Issue by limbooverlambda** [tikv/migration#403]
We are considering using TiCDC to replicate a subset of the keys stored into a particular tikv cluster to another tikv cluster to meet our need to maintain an active-passive setup for our service. 

The idea is start the changefeed for the key-ranges, keep monitoring the changefeed for the progress of the replication, disable the traffic(all R/W) going into the system and then keep the changefeed around until the sink has caught up with the source. 

**My question is, what is the way to determine that the replication has caught up with the source? Is there a definitive way to determine if all the changes for a key-range has been replicated to the destination?**

 Essentially once the destination has caught up with the source cluster, we would like to failover to the target cluster and use it as the service backend. Any pointers here will be very helpful.

@pingyu

**Comment by Smityz** [comment]
![image](https://github.com/tikv/migration/assets/22953824/90923085-c1d3-44a0-9e04-21c0041cfc47)

https://github.com/tikv/migration/blob/main/cdc/metrics/grafana/tikv-cdc.json#L2039

I think you can observe this metric. You can collect it by tikv-cdc process

**Comment by limbooverlambda** [comment]
Thanks. Can you explain what this metric does? Since I will be using a watcher to take automated action to perform the failover, how can I programmatically observe this threshold to perform the failover?

**Comment by Smityz** [comment]
It said, how long should you wait for data sync from now. 
However, if there is continuous data writing upstream, downstream will always have a delay of several seconds. 
Therefore, in your scenario, I suggest you stop the upstream writing for a period of time before switching.

**Comment by Smityz** [comment]
```
./cdc cli changefeed statistics
{
  "ops": 0,
  "count": 0,
  "sink_gap": "650ms",
  "replication_gap": "7250ms"
}
{
  "ops": 0,
  "count": 0,
  "sink_gap": "450ms",
  "replication_gap": "7334ms"
}
{
  "ops": 0,
  "count": 0,
  "sink_gap": "1000ms",
  "replication_gap": "7700ms"
}
```
You can also use cli to observe this gap.
And you can ref [https://github.com/tikv/migration/blob/1b33b2a92709b631cfab2b7d546ae0c230083353/cdc/pkg/cmd/cli/cli_changefeed_statistics.go#L92](url) to write your own codes to do loop query

**Comment by limbooverlambda** [comment]
This is very helpful. Does the replication_gap value tells me how far behind the CDC process is from the last write to the source cluster? I am curious as to how do I determine the time to wait before failing over, so that I am not missing any writes that got committed to the source cluster.

**Comment by limbooverlambda** [comment]
Following the link you posted, I ran into this 
https://github.com/tikv/migration/blob/1b33b2a92709b631cfab2b7d546ae0c230083353/cdc/pkg/cmd/cli/cli_changefeed_statistics.go#L117C2-L118C25

Here the replication_delay and the sink_gap are defined as follows:
```
sinkGap := oracle.ExtractPhysical(changefeed.ResolvedTs) - oracle.ExtractPhysical(changefeed.CheckpointTSO)
replicationGap := ts - oracle.ExtractPhysical(changefeed.CheckpointTSO)
```
And ts is:
`ts, _, err := o.pdClient.GetTS(ctx)`

I am assuming `ts` is the latest timestamp from PD. It will be great to get an understanding of what `changefeed.ResolvedTs` and `changefeed.CheckpointTSO` is.

**Comment by pingyu** [comment]
The replication gap from view of TiKV-CDC is not reliable enough for your scene. There would be data still in upstream TiKV and have not sent to TiKV-CDC yet.

I have never met such requirement like this before, but I think you can try this solution:

1. After the traffic to upstream is stopped, get a TSO from PD.
2. Observe the `checkpoint_ts` of the changefeed.

When `checkpoint_ts` is larger than the TSO at the beginning, the replication must have been done.

The `checkpoint_ts` can be acquired by `cdc cli` as @Smityz mentioned, and there is a http interface as well. Please refer to the [api doc](https://github.com/tikv/migration/tree/main/cdc/api) or [integration test case](https://github.com/tikv/migration/blob/1b33b2a92709b631cfab2b7d546ae0c230083353/cdc/tests/integration_tests/http_api/util/test_case.py#L67) for usage.

The `checkpoint_ts` is the watermark of data that has been replicated to downstream, i.e., all data with TSO <= `checkpoint_ts` must be already in downstream.

**Comment by limbooverlambda** [comment]
Thanks a lot @pingyu @Smityz . This has been incredibly helpful.
