### ISSUE TITLE
Support keep timestamp consistency to the downstream

### ISSUE THREAD

**Issue by Smityz** [tikv/migration#404]
Can we keep the timestamp consistent with upstream when transmitting data downstream through CDC? 
In this way, by specifying the method of reading through timestamp snapshots, the integrity of data synchronization can be regularly checked.

**Comment by pingyu** [comment]
I think no.

The TSO is a logical timestamp that is meaningful in the scope of the same PD (cluster) only. Use the TSO of another PD cluster will break the causal consistency.

Maybe we can keep the same TSO when replicating between two TiKV clusters under the same PD (currently it's not be supported neither). But in this scene, it seems that Raft replication is enough.

**Comment by Smityz** [comment]
In a typical scenario, there should be no other data written to the backup cluster. 
CDC should be the only data source, so we can ignore this consistency issue. 
If we don't do this, it will be difficult for us to perform data verification in a real-time writing cluster.
