### ISSUE TITLE
TiKV-BR: support RawKV API V2 & Cross API version migration

### ISSUE THREAD

**Issue by pingyu** [tikv/migration#66]
## Feature Request

**Is your feature request related to a problem? Please describe:**

1. [BR for RawKV](https://docs.pingcap.com/tidb/stable/use-br-command-line-tool#back-up-raw-kv-experimental-feature) is an experimental feature, not for production env.
2. No backup & restore tool for RawKV [API V2](https://github.com/tikv/rfcs/blob/master/text/0069-api-v2.md).
3. No migration tool between RawKV API V1/V1TTL to V2.

**Describe the feature you'd like:**

1. Support backup & restore for RawAPI V2.
2. Support data migration from API V1/V1TTL to V2.

**Describe alternatives you've considered:**

N/A.

**Teachability, Documentation, Adoption, Migration Strategy:**

TBD.

**Comment by pingyu** [comment]
@zz-jason @haojinming PTAL~

**Comment by zz-jason** [comment]
checksum should also be considered in the process of backup and restore, as discussed in https://github.com/tikv/migration/pull/69#discussion_r831839201

**Comment by zz-jason** [comment]
we need to make dependency clear and easy to update to newer versions. there are currently lots of `replace` statements in `br/go.mod`, which can be optimized out.

**Comment by pingyu** [comment]
This issue is done.
